version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "sisnutri"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports: 
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      
  backend:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:  
      - db