"""Initial migration 29032021

Revision ID: 22d7159a09e6
Revises: 5f162f11592d
Create Date: 2021-03-29 10:18:41.340677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22d7159a09e6'
down_revision = '5f162f11592d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendedor', sa.Column('comissao', sa.NUMERIC(precision=8, scale=3), nullable=True))
    op.drop_column('vendedor', 'comissa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendedor', sa.Column('comissa', mysql.DECIMAL(precision=8, scale=3), nullable=True))
    op.drop_column('vendedor', 'comissao')
    # ### end Alembic commands ###
