"""empty message

Revision ID: 5f162f11592d
Revises: 
Create Date: 2021-03-19 16:49:32.934926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f162f11592d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('idgrupoproduto', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'grupoprodutos', ['idgrupoproduto'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'idgrupoproduto')
    # ### end Alembic commands ###
