"""empty message

Revision ID: b0716db1a94c
Revises: 22d7159a09e6
Create Date: 2021-04-07 10:49:08.287053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0716db1a94c'
down_revision = '22d7159a09e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pessoa', 'email',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('pessoa', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_index('email', table_name='pessoa')
    op.drop_index('username', table_name='pessoa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'pessoa', ['username'], unique=True)
    op.create_index('email', 'pessoa', ['email'], unique=True)
    op.alter_column('pessoa', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('pessoa', 'email',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
